"""Embed a sample of real DIALS output as a C++ header.

Forty reflections and the geometry that produced them, so the conventions in
`src/geometry.hh` are checked against a file DIALS wrote on every build. That is
the only kind of check that can catch a wrong convention: the closed-loop test
in test_geometry.cc applies each convention twice, once forward and once
backward, so an error in one cancels itself.

Both the imported and the refined panel are embedded, because they are needed
for different things. `xyzobs.mm.value` is computed once at import and never
recomputed, so it must be reproduced from the IMPORTED panel; `xyzcal.px` comes
from refinement and must be reproduced from the REFINED one. Using the wrong
one leaves a 1.7e-3 mm discrepancy that looks like a flaw in the parallax model
and is not.

    python tests/make_real_data.py imported.expt indexed.expt indexed.refl \
        > tests/real_data.hh
"""

import json
import sys

import numpy as np
from mxeq import refl


def vec(values):
    return "{%s}" % ", ".join("%.17g" % v for v in values)


def panel_block(prefix, path):
    d = json.load(open(path))
    p = d["detector"][0]["panels"][0]
    return [
        f"inline constexpr double k{prefix}Fast[3] = {vec(p['fast_axis'])};",
        f"inline constexpr double k{prefix}Slow[3] = {vec(p['slow_axis'])};",
        f"inline constexpr double k{prefix}Origin[3] = {vec(p['origin'])};",
        f"inline constexpr double k{prefix}PixelSize[2] = {vec(p['pixel_size'])};",
        f"inline constexpr double k{prefix}Mu = %.17g;" % p["mu"],
        f"inline constexpr double k{prefix}Thickness = %.17g;" % p["thickness"],
    ]


def main(imported_path, indexed_path, refl_path, n_rows=40):
    d = json.load(open(indexed_path))
    p = d["detector"][0]["panels"][0]
    b, g, c = d["beam"][0], d["goniometer"][0], d["crystal"][0]
    osc = d["scan"][0]["properties"]["oscillation"]

    t = refl.load(refl_path)
    m = np.any(t["miller_index"] != 0, axis=1)
    hkl, px = t["miller_index"][m], t["xyzobs.px.value"][m]
    mm, rlp = t["xyzobs.mm.value"][m], t["rlp"][m]
    cal_px, cal_mm = t["xyzcal.px"][m], t["xyzcal.mm"][m]
    entering = t["entering"][m]

    # Spread the sample over the scan; the first n rows would all sit on the
    # first image or two and never exercise the goniometer rotation.
    order = np.argsort(px[:, 2])
    pick = order[np.linspace(0, len(order) - 1, n_rows).astype(int)]

    out = [
        "// GENERATED by tests/make_real_data.py. Do not edit.",
        "//",
        "// dials.index on a 300-image insulin sweep. Both panels are here: the",
        "// imported one reproduces xyzobs.mm (written once at import), the",
        "// refined one reproduces xyzcal.px.",
        "#pragma once",
        "",
        "#include <vector>",
        "",
        "namespace real {",
        "",
        "inline constexpr double kWavelength = %.17g;" % b["wavelength"],
        f"inline constexpr double kBeamDirection[3] = {vec(b['direction'])};",
        f"inline constexpr long kImageSize[2] = {{{p['image_size'][0]}, {p['image_size'][1]}}};",
        "inline constexpr double kGonioAxes[3][3] = {%s};"
        % ", ".join(vec(a) for a in g["axes"]),
        f"inline constexpr double kGonioAngles[3] = {vec(g['angles'])};",
        "inline constexpr int kScanAxis = %d;" % g["scan_axis"],
        "inline constexpr long kImageRange[2] = {%d, %d};"
        % tuple(d["scan"][0]["image_range"]),
        "inline constexpr double kOscStart = %.17g;" % osc[0],
        "inline constexpr double kOscWidth = %.17g;" % (osc[1] - osc[0]),
        f"inline constexpr double kRealSpaceA[3] = {vec(c['real_space_a'])};",
        f"inline constexpr double kRealSpaceB[3] = {vec(c['real_space_b'])};",
        f"inline constexpr double kRealSpaceC[3] = {vec(c['real_space_c'])};",
        "",
    ]
    out += panel_block("Imported", imported_path)
    out += [""]
    out += panel_block("Refined", indexed_path)
    out += [
        "",
        "struct Row {",
        "  int h, k, l;",
        "  double px_fast, px_slow, px_z;",
        "  double mm_fast, mm_slow, mm_phi;",
        "  double cal_mm_fast, cal_mm_slow;",
        "  double cal_px_fast, cal_px_slow;",
        "  double rlp[3];",
        "  bool entering;",
        "};",
        "",
        "inline const std::vector<Row> &rows() {",
        "  static const std::vector<Row> data = {",
    ]
    for i in pick:
        out.append(
            "      {%d, %d, %d, %.17g, %.17g, %.17g, %.17g, %.17g, %.17g, "
            "%.17g, %.17g, %.17g, %.17g, {%.17g, %.17g, %.17g}, %s},"
            % (
                hkl[i][0],
                hkl[i][1],
                hkl[i][2],
                px[i][0],
                px[i][1],
                px[i][2],
                mm[i][0],
                mm[i][1],
                mm[i][2],
                cal_mm[i][0],
                cal_mm[i][1],
                cal_px[i][0],
                cal_px[i][1],
                rlp[i][0],
                rlp[i][1],
                rlp[i][2],
                "true" if entering[i] else "false",
            )
        )
    out += ["  };", "  return data;", "}", "", "}  // namespace real"]
    print("\n".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:4])
