"""Embed a sample of a multi-sweep dataset as a C++ header.

These datasets exist in the tests to exercise the goniometer, which the single
insulin sweep cannot: every setting angle there is zero, so the fixed and
setting rotations both collapse to the identity and any arrangement of them
passes.

    python tests/make_sweep_data.py indexed.expt indexed.refl NAMESPACE \\
        > tests/real_NAMESPACE.h

The axis count is read from the file rather than fixed, because the two
datasets in use have different ones and hard-coding two would have quietly
truncated the three-axis case.
"""

from __future__ import annotations

import json
import sys

import numpy as np
from mxeq import refl


def vec(values):
    return "{%s}" % ", ".join("%.17g" % v for v in values)


def main(expt_path, refl_path, namespace, per_sweep=12):
    d = json.load(open(expt_path))
    crystal = d["crystal"][0]

    table = refl.load(refl_path)
    indexed = np.any(table["miller_index"] != 0, axis=1)

    out = [
        "// GENERATED by tests/make_sweep_data.py. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <vector>",
        "",
        f"namespace {namespace} {{",
        "",
        f"inline constexpr double kRealSpaceA[3] = {vec(crystal['real_space_a'])};",
        f"inline constexpr double kRealSpaceB[3] = {vec(crystal['real_space_b'])};",
        f"inline constexpr double kRealSpaceC[3] = {vec(crystal['real_space_c'])};",
        "",
        "struct Row {",
        "  int h, k, l;",
        "  double px_fast, px_slow, px_z;",
        "  double rlp[3];",
        "};",
        "",
        "struct Sweep {",
        "  double wavelength;",
        "  std::array<double, 3> beam_direction;",
        "  // panel",
        "  std::array<double, 3> fast, slow, origin;",
        "  std::array<double, 2> pixel_size;",
        "  double mu, thickness;",
        "  std::array<long, 2> image_size;",
        "  // goniometer, axes ordered from the sample outwards to the laboratory",
        "  std::vector<std::array<double, 3>> axes;",
        "  std::vector<double> angles;",
        "  int scan_axis;",
        "  // scan",
        "  std::array<long, 2> image_range;",
        "  double osc_start, osc_width;",
        "  std::vector<Row> rows;",
        "};",
        "",
        "inline const std::vector<Sweep> &sweeps() {",
        "  static const std::vector<Sweep> data = {",
    ]

    for index, experiment in enumerate(d["experiment"]):
        panel = d["detector"][experiment["detector"]]["panels"][0]
        beam = d["beam"][experiment["beam"]]
        gonio = d["goniometer"][experiment["goniometer"]]
        scan = d["scan"][experiment["scan"]]
        oscillation = scan["properties"]["oscillation"]
        width = (oscillation[-1] - oscillation[0]) / (len(oscillation) - 1)

        select = indexed & (table["id"] == index)
        rows = np.nonzero(select)[0]
        # Spread along the scan rather than taking the first few, which would
        # all sit on one image and never exercise the rotation.
        rows = rows[np.argsort(table["xyzobs.px.value"][rows][:, 2])]
        rows = rows[np.linspace(0, len(rows) - 1, per_sweep).astype(int)]

        out.append("      {")
        out.append("       %.17g, %s," % (beam["wavelength"], vec(beam["direction"])))
        out.append(f"       {vec(panel['fast_axis'])}, {vec(panel['slow_axis'])},")
        out.append(f"       {vec(panel['origin'])}, {vec(panel['pixel_size'])},")
        out.append("       %.17g, %.17g," % (panel["mu"], panel["thickness"]))
        out.append(
            "       {%d, %d}," % (panel["image_size"][0], panel["image_size"][1])
        )
        out.append("       {%s}," % ", ".join(vec(a) for a in gonio["axes"]))
        out.append(f"       {vec(gonio['angles'])}, {gonio['scan_axis']},")
        out.append(
            "       {%d, %d}, %.17g, %.17g,"
            % (scan["image_range"][0], scan["image_range"][1], oscillation[0], width)
        )
        out.append("       {")
        for r in rows:
            hkl = table["miller_index"][r]
            px = table["xyzobs.px.value"][r]
            rlp = table["rlp"][r]
            out.append(
                "        {%d, %d, %d, %.17g, %.17g, %.17g, {%.17g, %.17g, %.17g}},"
                % (hkl[0], hkl[1], hkl[2], px[0], px[1], px[2], rlp[0], rlp[1], rlp[2])
            )
        out.append("       },")
        out.append("      },")

    out += ["  };", "  return data;", "}", "", f"}}  // namespace {namespace}"]
    print("\n".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:4])
