"""Embed a sample of the l-cysteine multi-sweep data as a C++ header.

This dataset exists in the tests for one reason: it is the only thing that can
test the goniometer decomposition. The insulin sweep has every setting angle at
zero, so the fixed and setting rotations both collapse to the identity and any
arrangement of them passes.

Four sweeps from one crystal on a fixed-chi goniometer (Winter et al., 2018,
section 4.3): a 180 degree phi scan at 2theta = 0, then three 170 degree omega
scans at phi = 0, 120 and 240 with 2theta = 30. What makes it discriminating:

* Sweeps 1 and 2 have a non-zero phi setting below the scan axis, so the fixed
  rotation is not the identity. Swapping fixed and setting, or dropping the
  fixed rotation, breaks those two and leaves sweeps 0 and 3 untouched.
* All three omega sweeps carry angles[scan_axis] = -145, which is the scan
  start and must be ignored. Composing it into the fixed rotation breaks
  sweeps 0, 1 and 2 -- and sweep 0 is the ONLY case that tests that rule,
  because it is the only sweep where the fixed rotation is otherwise identity
  and the scan-axis angle is not.
* Sweep 3 scans a different axis entirely (scan_axis 0, not 1), so the code
  cannot assume the scan axis is last.
* Two detectors, one of them at a 2theta offset, on a 320 micron sensor with a
  different mu from the insulin data.

    python tests/make_cysteine_data.py indexed.expt indexed.refl \\
        > tests/real_cysteine.h
"""

from __future__ import annotations

import json
import sys

import numpy as np
from mxeq import refl


def vec(values):
    return "{%s}" % ", ".join("%.17g" % v for v in values)


def main(expt_path, refl_path, per_sweep=12):
    d = json.load(open(expt_path))
    beam = d["beam"][0]
    crystal = d["crystal"][0]

    table = refl.load(refl_path)
    indexed = np.any(table["miller_index"] != 0, axis=1)

    out = [
        "// GENERATED by tests/make_cysteine_data.py. Do not edit.",
        "//",
        "// l-cysteine, four sweeps on a fixed-chi goniometer. The only data",
        "// here that can test the goniometer decomposition; see the script.",
        "#pragma once",
        "",
        "#include <vector>",
        "",
        "namespace cysteine {",
        "",
        "inline constexpr double kWavelength = %.17g;" % beam["wavelength"],
        f"inline constexpr double kBeamDirection[3] = {vec(beam['direction'])};",
        f"inline constexpr double kRealSpaceA[3] = {vec(crystal['real_space_a'])};",
        f"inline constexpr double kRealSpaceB[3] = {vec(crystal['real_space_b'])};",
        f"inline constexpr double kRealSpaceC[3] = {vec(crystal['real_space_c'])};",
        "",
        "struct Row {",
        "  int h, k, l;",
        "  double px_fast, px_slow, px_z;",
        "  double rlp[3];",
        "};",
        "",
        "struct Sweep {",
        "  // panel",
        "  double fast[3], slow[3], origin[3], pixel_size[2], mu, thickness;",
        "  long image_size[2];",
        "  // goniometer: two axes, their setting angles, and which is scanned",
        "  double axes[2][3];",
        "  double angles[2];",
        "  int scan_axis;",
        "  // scan",
        "  long image_range[2];",
        "  double osc_start, osc_width;",
        "  std::vector<Row> rows;",
        "};",
        "",
        "inline const std::vector<Sweep> &sweeps() {",
        "  static const std::vector<Sweep> data = {",
    ]

    for index, experiment in enumerate(d["experiment"]):
        panel = d["detector"][experiment["detector"]]["panels"][0]
        gonio = d["goniometer"][experiment["goniometer"]]
        scan = d["scan"][experiment["scan"]]
        oscillation = scan["properties"]["oscillation"]
        width = (oscillation[-1] - oscillation[0]) / (len(oscillation) - 1)

        select = indexed & (table["id"] == index)
        rows = np.nonzero(select)[0]
        # Spread along the scan rather than taking the first few, which would
        # all sit on one image and never exercise the rotation.
        z = table["xyzobs.px.value"][rows][:, 2]
        rows = rows[np.argsort(z)]
        rows = rows[np.linspace(0, len(rows) - 1, per_sweep).astype(int)]

        out.append("      {")
        out.append(f"       {vec(panel['fast_axis'])}, {vec(panel['slow_axis'])},")
        out.append(f"       {vec(panel['origin'])}, {vec(panel['pixel_size'])},")
        out.append("       %.17g, %.17g," % (panel["mu"], panel["thickness"]))
        out.append(
            "       {%d, %d}," % (panel["image_size"][0], panel["image_size"][1])
        )
        out.append(
            "       {%s, %s}," % (vec(gonio["axes"][0]), vec(gonio["axes"][1]))
        )
        out.append(f"       {vec(gonio['angles'])}, {gonio['scan_axis']},")
        out.append(
            "       {%d, %d}, %.17g, %.17g,"
            % (scan["image_range"][0], scan["image_range"][1], oscillation[0], width)
        )
        out.append("       {")
        for r in rows:
            hkl = table["miller_index"][r]
            px = table["xyzobs.px.value"][r]
            rlp = table["rlp"][r]
            out.append(
                "        {%d, %d, %d, %.17g, %.17g, %.17g, {%.17g, %.17g, %.17g}},"
                % (hkl[0], hkl[1], hkl[2], px[0], px[1], px[2], rlp[0], rlp[1], rlp[2])
            )
        out.append("       },")
        out.append("      },")

    out += ["  };", "  return data;", "}", "", "}  // namespace cysteine"]
    print("\n".join(out))


if __name__ == "__main__":
    main(*sys.argv[1:3])
