# Turn a compiled .metallib into a C++ translation unit, so that the binary
# carries its own kernels.
#
# The alternative is loading a .metallib from beside the executable at run time,
# which means a second file to install, to keep in step with the binary, and to
# find when the working directory is not what anyone expected. A binary
# that reports its version should not be able to disagree with its own shaders.
#
# Run as: cmake -DINPUT=<file.metallib> -DOUTPUT=<file.cc> -P embed_metallib.cmake

# SYMBOL names the arrays; spotfinder_dext_metallib unless told.
if(NOT DEFINED SYMBOL)
    set(SYMBOL spotfinder_dext_metallib)
endif()

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_metallib.cmake needs -DINPUT= and -DOUTPUT=")
endif()

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" characters)
math(EXPR length "${characters} / 2")

# Twelve bytes a line keeps the generated file readable in a diff and well
# inside any compiler's line-length limit.
string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)"
                     "\\1\n    " bytes "${bytes}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/embed_metallib.cmake from a Metal shader.
// Do not edit, and do not commit: it is rebuilt whenever the shader changes.

extern \"C\" const unsigned char ${SYMBOL}[] = {
    ${bytes}
};
extern \"C\" const unsigned long ${SYMBOL}_size = ${length}ul;
")
